### ISSUE TITLE
Graph creation is not scalable

### ISSUE THREAD

**Issue by fotol1** [gusye1234/LightGCN-PyTorch#1]
Hello!

Thank you for posting the code of LightGCN. I would like to suggest an improvement. I found that the following line of the code can cause a MemoryError in case of a large number users or items:

https://github.com/gusye1234/LightGCN-PyTorch/blob/c5c8325de115672783656814d40488c8d86a1c34/code/dataloader.py#L150

To escape using `.to_dense()` I changed these lines of the code in my local version:

https://github.com/gusye1234/LightGCN-PyTorch/blob/c5c8325de115672783656814d40488c8d86a1c34/code/dataloader.py#L145-L160

To these:

```
first_sub = np.vstack((trainUser,trainItem+n_users))
second_sub = np.vstack((item_dim+n_users, user_dim))
index = np.concatenate([first_sub, second_sub],1)
data = np.ones(index.shape[-1]).astype(np.int32)
Graph = sps.csr_matrix((data,index))
D = Graph.sum(1)
D[D==0] = 1.
D_sqrt = sps.diags(1/np.sqrt(D.A.ravel()))
Graph = D_sqrt * Graph * D_sqrt
index = torch.Tensor(Graph.nonzero()).long().T
data = torch.Tensor(Graph[Graph.nonzero()]).squeeze(0)
Graph = torch.sparse.FloatTensor(index.t(),
                         data,
                         torch.Size([n_users+n_items, n_users+n_items]))
Graph = Graph.coalesce().to('cpu')
```

They seem to be the same thing. However, the second option does not create a matrix of size (N + M) ** 2. So, your model could be run on large datasets.

**Comment by gusye1234** [comment]
Sure, thanks for the advice. 
This problem seems like a careless mistake since we don't actually need a dense matrix.
But this line only happen for the `LastFM` dataset, which is a relatively small dataset.
