### ISSUE TITLE
The performance gap of this repo w.r.t  the orginal paper

### ISSUE THREAD

**Issue by bnu-wangxun** [gusye1234/LightGCN-PyTorch#10]
As in the paper,  the recall value of 1-layer LGCN on Yelp is 0.063, while 0.05604 in this repo. Where the gap come from?

**Comment by gusye1234** [comment]
Hi, thanks for the reminder. 
However, the results in the paper were reported by the [TensorFlow version](https://github.com/kuandeng/LightGCN), and this PyTorch version was developed after it. Actually, we may not share the same random state at all. I will suggest you try different random seeds to see how it's going. 
We decided to post this repo's results when the metrics are basically the same as the TensorFlow version.
