### ISSUE TITLE
The program report "Floating point exception (core dumped)" when run lightGCN on mine dataset

### ISSUE THREAD

**Issue by snooker-player** [gusye1234/LightGCN-PyTorch#12]
This error was reported when I leveraged the C++ sampling program.
What should I do to use the C++ program on my own dataset?

**Comment by gusye1234** [comment]
Could you post a more detailed exception?

**Comment by snooker-player** [comment]
> Could you post a more detailed exception?

Thanks for your reply. It just said that "Floating point exception (core dumped)". I upload the dataset on [https://github.com/snooker-player/gowalla](url)
