### ISSUE TITLE
could not find a version torch==1.4.0

### ISSUE THREAD

**Issue by AlexWeig** [gusye1234/LightGCN-PyTorch#2]
i used `pip install -r requirements.txt` in an anaconda environment, but an error occurred:

> ERROR: Could not find a version that satisfies the requirement torch==1.4.0 (from -r requirements.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)

> ERROR: No matching distribution found for torch==1.4.0 (from -r requirements.txt (line 1))

i tried to use python3.8, pyhton3.7, python 3.6 and looked it up on Google, it still didn't work

**Comment by gusye1234** [comment]
Well, it's confusing.
You may try just `pip install torch` to install the latest release.
