### ISSUE TITLE
An error when running on amazon-book

### ISSUE THREAD

**Issue by xiransong** [gusye1234/LightGCN-PyTorch#22]
Hi! There's an error when running on the amazon-book dataset.

The Python version is 3.8.12 .

```
cd code && python main.py --decay=1e-3 --lr=0.001 --layer=2 --seed=2020 --dataset="amazon-book" --topks="[20, 100, 300]" --recdim=64
```

```
Cpp extension not loaded
>>SEED: 2020
loading [../data/amazon-book]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    import register
  File "/home/sxr/code/LightGCN/code/register.py", line 8, in <module>
    dataset = dataloader.Loader(path="../data/"+world.dataset)
  File "/home/sxr/code/LightGCN/code/dataloader.py", line 261, in __init__
    items = [int(i) for i in l[1:]]
  File "/home/sxr/code/LightGCN/code/dataloader.py", line 261, in <listcomp>
    items = [int(i) for i in l[1:]]
ValueError: invalid literal for int() with base 10: '' 
```

**Comment by gongkaiqi** [comment]
读取Amazon-Books的test数据时，部分用户没有交互的项目，所以这里读数据报错了。我找到有13647、41589、50736、52234号用户，你可以看看。

**Comment by Run542968** [comment]
> 读取Amazon-Books的test数据时，部分用户没有交互的项目，所以这里读数据报错了。我找到有13647、41589、50736、52234号用户，你可以看看。

I don't think so. The above "if" statement has excluded users without interaction in "test.txt".

**Comment by Run542968** [comment]
> 读取Amazon-Books的test数据时，部分用户没有交互的项目，所以这里读数据报错了。我找到有13647、41589、50736、52234号用户，你可以看看。

The problem is not here, I solve this problem by changing  "l.strip('\n')" to "l.strip()". You can try it.

**Comment by d9249** [comment]
I have the same problem, so if you solved it, can you share the solution?

**Comment by WangFengF** [comment]
把那几行没有交互的用户id后面的空格去掉就行了。

**Comment by xiransong** [comment]
I think changing all the "l.strip('\n')" to "l.strip()" in dataloader.py is a good solution.
