### ISSUE TITLE
Statistics of the datasets

### ISSUE THREAD

**Issue by Book1996** [gusye1234/LightGCN-PyTorch#5]
I downloaded the amazon book dataset of 10-core. But i get different statistics of the datasets: item_num = 128939, user_num = 158650, sample = 4701968. Thus, could you give me the code of preprocessing of amazon book dataset, please. It is really important to me.

**Comment by gusye1234** [comment]
Hi, maybe you can just use the amazon-book dataset in the `data` ? 

All the code I used for this model is already in this repo. I don't have the preprocessing code. Sorry

**Comment by Book1996** [comment]
Do you know who can provide the preprocessing code?

**Comment by gusye1234** [comment]
You can check this [repo](https://github.com/xiangwang1223/neural_graph_collaborative_filtering)

**Comment by Book1996** [comment]
Thanks, i haved ask him for the code. But, i don't get any reply.
