### ISSUE TITLE
Something wrong with 'amazon-book' dataset

### ISSUE THREAD

**Issue by KylinA1** [gusye1234/LightGCN-PyTorch#9]
Everything is fine when running on gowallo dataset.
Got an error, while parsing amazon dataset,
specifclly, "dataloder.py"

`ValueError: invalid literal for int() with base 10: ''`

**Comment by KylinA1** [comment]
The reason is the in line13648, there is no item for the user with id "13647" .

**Comment by jeongwhanchoi** [comment]
the below try/exception code could solve the error

```
# Loader class in Dataloader.py
                    try:
                        items = [int(i) for i in l[1:]]
                    except Exception:
                        continue
```
